### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by Cheesebaron** [steffkelsey/Xamarin_MvvmCross_MaterialDesign#1]
Hey Steff,

Just to let you know, when you redistribute code that was licensed, especially code taken from MvvmCross which is licensed with the MIT license, you must keep those copyright and license headers and include the license.

If you need help with that please do tell.

**Comment by steffkelsey** [comment]
Sorry this is work in progress and probably should not be public yet. I'll add the license + headers today.

**Comment by steffkelsey** [comment]
Cheesebaron, 

I added the license and updated the headers on the Mvx files. Let me know if I missed anything.

And thanks for all your great work. I am pretty new to the MvvmCross community and your code and activity on the forums has been crucial in getting up to speed. I really appreciate it.

**Comment by Cheesebaron** [comment]
https://github.com/steffkelsey/Xamarin_MvvmCross_MaterialDesign/blob/master/MvxMaterial.DroidFullFrag/Presenters/

https://github.com/steffkelsey/Xamarin_MvvmCross_MaterialDesign/blob/master/MvxMaterial.DroidFullFrag/Views/BaseCachingFragmentAcivity.cs

These will probably need some as well. However, I do see I forgot to add them when I pushed them to MvvmCross. Filed a bug here: https://github.com/MvvmCross/MvvmCross/issues/950

Just for reference these are the MvvmCross counterparts:

https://github.com/MvvmCross/MvvmCross/tree/3.5/Cirrious/Cirrious.MvvmCross.Droid.FullFragging/Presenter

https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Droid.FullFragging/MvxCachingFragmentActivity.cs

**Comment by steffkelsey** [comment]
Right on. I added the headers. 

I couldn't use the MvvmCross versions of those two classes because I couldn't see a way to use them and also have Toolbar support with SupportActionBar, finer control of fragment transitions, and Android Back button support.
