### ISSUE TITLE
Use of viewmodels in fragments

### ISSUE THREAD

**Issue by martijn00** [steffkelsey/Xamarin_MvvmCross_MaterialDesign#2]
There are some nice examples in here, but i noticed that MvxFragment class doesn't make use of viewmodels the correct way.

This should work:
`public class SomeFragment : MvxFragment<SomeViewModel>
{}`

**Comment by steffkelsey** [comment]
Martin,
Not sure what you mean. All my fragments in the example do extend MvxFragment. 
Also this thing is only about 1/3 complete.

**Comment by martijn00** [comment]
See for example: https://github.com/steffkelsey/Xamarin_MvvmCross_MaterialDesign/blob/master/MvxMaterial.DroidFullFrag/Views/Fragments/MailListView.cs

In line 22 you do:
    `var viewModel = (MailListViewModel)this.ViewModel;`

Which is not needed if you change line 12 from: 
    `public class MailListView : MvxFragment`
To: 
    `public class MailListView : MvxFragment<MailListViewModel>`

**Comment by martijn00** [comment]
I just noticed that the markdown was wrong which made it hard for you to see what i ment. Sorry about that.

**Comment by martijn00** [comment]
Just as a sidenote / help for you: https://gist.github.com/kjeremy
and: https://gist.github.com/geirsagberg
have some nice gists which you might want to use for material design with Mvvmcross.

**Comment by steffkelsey** [comment]
Oh, right on. I didn't know I could use generics to avoid casting the ViewModel later. I just took a closer look at the MvxFragment source and saw the line near the bottom:
'public abstract class MvxFragment<TViewModel>: MvxFragment
        , IMvxFragmentView<TViewModel> where TViewModel : class, IMvxViewModel'
That's slick. Thanks for pointing that out!

And before you changed the markdown, I just thought you might be a little crazy.

**Comment by steffkelsey** [comment]
Oh, right on. I didn't know I could use generics to avoid casting the ViewModel later. I just took a closer look at the MvxFragment source and saw the line near the bottom:
`public abstract class MvxFragment<TViewModel>: MvxFragment
        , IMvxFragmentView<TViewModel> where TViewModel : class, IMvxViewModel`
That's slick. Thanks for pointing that out!

And before you changed the markdown, I just thought you might be a little crazy.
