### ISSUE TITLE
Where does the magic happen with fragment ViewModels?

### ISSUE THREAD

**Issue by Toine-db** [steffkelsey/Xamarin_MvvmCross_MaterialDesign#3]
It works fine with API 19 and higher, but I'm converting it to API 15 and got it to work except for the automatic ViewModel loading that this solutions seems to have somewhere.... Where does the ViewModel instance come from (ie; the LoginViewModel), because it suddenly is created after Fragments base.OnCreate(savedInstanceState) ? 

I can do it in "public override void Show(MvxViewModelRequest request)" like normal, but I realy want to know how its done at your end.

PS: I'm using a fork of the 3.5 MVVMCross.

**Comment by martijn00** [comment]
I suspect you need to look at the generics that where introduced in 3.5 and in this example after #2

**Comment by Toine-db** [comment]
@martijn00 I used this example after #2 and there isn't anything to find that loads the ViewModels (like viewModelLoader.LoadViewModel(request, mvxBundle) ). 
And also I'm using the 3.5 MVVMCross version, so I haven't got a clue where its going wrong.

**Comment by martijn00** [comment]
I think it would be better if you explain your problem on StackOverflow so we can discuss it there. But anyways, this is how the MvxFragment looks like in this example: 
`public class MailListView : MvxFragment<MailListViewModel>`

As you can see the MailListViewModel is used as generic parameter. MvvmCross hereafter does the loading in the code. You don't see anything for that in your own code.

**Comment by Toine-db** [comment]
@martijn00 Your right, lets continue on StackOverflow because it seems to be more a MVVMCross thing

PS: I found the fix; [MvxOwnedViewModelFragment] above the MvxFragment makes the fragment load its ViewModel. (was a fix in after 3.5 to switch functionalities)
